# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_worker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'agent_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61gent_worker.proto\x12\x0c\x61gent_worker\"p\n\x13\x44ispatchStepRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0f\n\x07step_id\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12\x17\n\x0forganization_id\x18\x04 \x01(\t\x12\r\n\x05input\x18\x05 \x01(\x0c\"Y\n\x0eStepEventProto\x12\x0f\n\x07step_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x14\n\x12HealthCheckRequest\"&\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x32\xbb\x01\n\x12\x41gentWorkerService\x12Q\n\x0c\x44ispatchStep\x12!.agent_worker.DispatchStepRequest\x1a\x1c.agent_worker.StepEventProto0\x01\x12R\n\x0bHealthCheck\x12 .agent_worker.HealthCheckRequest\x1a!.agent_worker.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISPATCHSTEPREQUEST']._serialized_start=36
  _globals['_DISPATCHSTEPREQUEST']._serialized_end=148
  _globals['_STEPEVENTPROTO']._serialized_start=150
  _globals['_STEPEVENTPROTO']._serialized_end=239
  _globals['_HEALTHCHECKREQUEST']._serialized_start=241
  _globals['_HEALTHCHECKREQUEST']._serialized_end=261
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=263
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=301
  _globals['_AGENTWORKERSERVICE']._serialized_start=304
  _globals['_AGENTWORKERSERVICE']._serialized_end=491
# @@protoc_insertion_point(module_scope)
